# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# orbs:
# Declare a dependency on the welcome-orb
# welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
# workflows:
# Name the workflow "welcome"
# welcome:
# Run the welcome/run job in its own container
# jobs:
#   - welcome/run
#----------------------------------------GHis-------
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run:
          name: command1
          command: |
            echo 'Ghis tries to use a command'
            echo 'Command 1 runs sucessfully'
      - run:
          name: command2
          command: |
            ls -al
            echo 'Commad2 ends!!...'
      - run:
          name: Compile all Java classes
          command: |
            java -cp classes src/main/fopt
      - run:
          name: Compile all Tests classes
          command: |
            java -cp classes src/test/fopt

  test:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: A Command inside Test just for Fun
          command: |
            echo "Ghislain"
            ls 
            pwd
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
