# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
# orbs:
# Declare a dependency on the welcome-orb
# welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
# workflows:
# Name the workflow "welcome"
# welcome:
# Run the welcome/run job in its own container
# jobs:
#   - welcome/run
#----------------------------------------GHis-------
jobs:
  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Ghis Command First Sample
          command: |
            echo 'Ghis tries to use a command'
            echo 'Command 1 runs sucessfully'
      - run:
          name: Compile all Java class Files
          command: |
            cd src/main
            find -name "*.java" > sources.txt
            javac -verbose -d bin @sources.txt
  test:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: A Command to run a test
          command: |
            echo "Ghislain"
            ls 
            pwd
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
